<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$title?></title>
    <link rel="shortcut icon" href="favicon.ico"> <link href="/css/bootstrap.min_AD7CC56B.css" rel="stylesheet">
    <link href="/css/font-awesome.min_10DD9C46.css" rel="stylesheet">

    <!-- Data Tables -->
    <link href="/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">

    <link href="/css/animate.min.css" rel="stylesheet">
    <link href="/css/style.min_0AF76BA4.css" rel="stylesheet"><base target="_blank">
</head>
<body class="gray-bg">
<?=$_content_?>
<script src="/js/jquery.min_FF924783.js"></script>
<script src="/js/bootstrap.min_AD7CC56B.js"></script>
<script src="/js/plugins/jeditable/jquery.jeditable.js"></script>
<script src="/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script src="/js/content.min_4E9A9529.js"></script>
<?php if (isset($jspaths)):?>
<?php foreach ($jspaths as $js):?>
<script src="<?=$js?>" type="text/javascript"></script>
<?php endforeach;?>
<?php endif;?>
</body>
</html>
