<?php use Helper\Html; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->title?:null?> - Backend</title>
        <?= Html::css('/resource/semantic/semantic.min.css')?>
    </head>
    <body>
    <div class="ui grid">
        <div class="four vertical fluid menu">
            <div class="item">
                <div class="header">Products</div>
                <div class="menu">
                    <a class="item">Enterprise</a>
                    <a class="item">Consumer</a>
                </div>
            </div>
            <div class="item">
                <div class="header">CMS Solutions</div>
                <div class="menu">
                    <a class="item">Rails</a>
                    <a class="item">Python</a>
                    <a class="item">PHP</a>
                </div>
            </div>
            <div class="item">
                <div class="header">Hosting</div>
                <div class="menu">
                    <a class="item">Shared</a>
                    <a class="item">Dedicated</a>
                </div>
            </div>
            <div class="item">
                <div class="header">Support</div>
                <div class="menu">
                    <a class="item">E-mail Support</a>
                    <a class="item">FAQs</a>
                </div>
            </div>
        </div>

    <div class="twelve wide stretched column">
        <a href="javascript:;" onclick="$('.ui.sidebar').sidebar('toggle');">aaaa</a>
    </div>

        <?php echo $_content_;?>

    </div>
        <footer>Yaf v<?=YAF_VERSION?></footer>
        <?= Html::javascript("/js/jquery-1.12.4.min.js")?>
        <?= Html::javascript("/resource/semantic/semantic.min.js")?>
        <?php if (isset($jspaths)) {foreach ($jspaths as $jspath) {?>
        <?= Html::javascript("/js/".$jspath)?>
        <?php }}?>
        <script>

        </script>
    </body>
</html>
